version: "3"

services:
  database:
    image: "postgres:latest"

    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: histories
      POSTGRES_PASSWORD: histories
      POSTGRES_DB: histories
